kind: pipeline
type: exec
name: Deploying Staging

platform:
  os: linux
  arch: amd64

clone:
  disable: true

trigger:
  event:
    include:
      - tag
  ref:
    include:
      - refs/tags/[0-9]*.[0-9]*.[0-9]*-rc.[0-9]*

steps:
  - name: greeting
    commands:
      - whoami
  - name: preperation
    environment:
      LOCATION: /opt/data/teman-data-landing-page
    commands:
      - pwd
      - ls -la
      - echo $LOCATION
      - echo $DRONE_TAG >> $LOCATION/.version-history
      - |
        if [ $(wc -l < $LOCATION/.version-history) -gt 2 ]; 
        then echo removing: $(head -n 1 $LOCATION/.version-history); 
        else echo $DRONE_TAG >> $LOCATION/.version-history; fi
