kind: pipeline
type: exec
name: Deploying Staging

platform:
  os: linux
  arch: amd64

clone:
  disable: true

trigger:
  event:
    include:
      - tag
  ref:
    include:
      - refs/tags/[0-9]*.[0-9]*.[0-9]*-rc.[0-9]*

steps:
  - name: greeting
    commands:
      - whoami
  - name: preperation
    environment:
      VERSION_HISTORY: /opt/data/teman-data-landing-page/.version-history
    commands:
      - touch $VERSION_HISTORY
      - |
        if [ $(wc -l < "$VERSION_HISTORY") -gt 2 ]; then
          sed -i '1d' "$VERSION_HISTORY"
          OLD_TAG=$(head -n 1 "$VERSION_HISTORY")
          IMAGE_OLD="teman-data-landing-page:$OLD_TAG"
          echo "image old is"
          echo $IMAGE_OLD
          echo "$DRONE_TAG" >> "$VERSION_HISTORY"
        else
          echo "$DRONE_TAG" >> "$VERSION_HISTORY"
        fi
